### ISSUE TITLE
Don't see keyboard after installation

### ISSUE THREAD

**Issue by keoladonaghy** [E-Haci/chrome-os-azerbaijani-keyboard#3]
Aloha! I was looking at modifying this keyboard in order to develop a keyboard for Hawaiian speakers. The way you've done it seems very relevant to what I need to do to get our Hawaiian vowel/diacritics - using the AltGr key.

I am able to load this keyboard in Extensions, however, it does not show up when I got to settings/languages - I cannot see nor select it. I have installed other "extra" keyboards I have found on github and they seem to display OK.

Any help you can provide is appreciated. We have thousands of Hawaiian language students, and many of our schools are moving to Chrome.

Mahalo (thank you!)  Keola

PS, I'm using a Samsung Chomebook

**Comment by E-Haci** [comment]
Hi. Have you followed all 4 steps i listed?
If you want, you can send me your Hawaiian version, i will test it on my chromebook.

**Comment by keoladonaghy** [comment]
Aloha and mahalo (thanks) for your reply. Yes, I tried all four steps. I went to Advanced Settings, and the Azerbaijani keyboard was not shown in the list after restart.

I've not done the modifications for the Hawaiian keyboard yet - I wanted to try yours first and see how it worked. It looks from the code that use of the AltGr key does generate different characters, which is what we want - if someone presses AltGr and a vowel we want it to generate that vowel with the macron. Same with AltGr+Shift = upper case vowel with macron.

When I get home I will change the code to the way I think it needs to be for our purposes and send it to you. Itʻs been many years since I've done any JS coding and even then I'd say I was intermediate level with it.

Your help is much appreciated!
Keola

**Comment by E-Haci** [comment]
_"I went to Advanced Settings, and the Azerbaijani keyboard was not shown in the list after restart."_
Chrome has changed settings UI since last time. Now you can find that in INPUT METHODS tab.  

Just go to settings and search for "input methods" - you will see where you need to add new layout. 
And make sure you are browsing **OS settings**, not **browser settings**.

With the same method i have just managed to install your copy on my chromebook.

Although i will not be able to provide any help on character codes and altkeys, but i can definitely help you to install Azerbaijani version. After that you will easily be able to play with codes and create your own version.

**Comment by keoladonaghy** [comment]
Aloha Elvin, mahalo again for all this. I did make a little progress since my last email and hopefully will be able to get the coding right on this to produce a Hawaiian keyboard based on yours. I'm very grateful for your confirmation below and the fact that you shared the code in the first place.

Thank you so much!
